#!/usr/bin/env python3
"""
PDF to Researchers CSV Script

This script processes a directory of research paper PDFs and creates a researchers.csv file
similar to the one generated by the main pipeline. It extracts researchers from both the
main papers and their cited references.

Usage:
    python scripts/pdf_to_researchers.py /path/to/pdf/directory [--output OUTPUT_FILE]

Arguments:
    pdf_directory: Path to directory containing PDF files
    --output: Output CSV file path (default: data/researchers.csv)
    --config: Config file path (default: auto-detect)
    --max-papers: Maximum number of PDFs to process (default: all)
"""

import os
import sys
import argparse
import pandas as pd
from pathlib import Path
from tqdm import tqdm
from collections import defaultdict
from typing import Dict, Any, List, Tuple
import time

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from utils import (
    load_config,
    get_openai_client,
    extract_text_from_pdf,
    extract_arxiv_id_from_text,
    extract_arxiv_id_from_filename,
    parse_paper_metadata,
    extract_citations_from_text,
    call_llm,
    parse_json_response,
    save_csv_checkpoint
)

def extract_researchers_from_paper_metadata(metadata: Dict[str, Any], client, config) -> List[Dict[str, Any]]:
    """Extract researchers from paper metadata using the same logic as the main pipeline"""
    # Load and format the prompt template
    prompt_template = """You are analyzing academic papers to extract researcher information. For each paper, identify the key researchers and their details.

Paper Details:
Title: {title}
Authors: {authors}
Abstract: {abstract}
ArXiv ID: {arxiv_id}
Published: {published_date}

For each author, extract:
- Full name (as listed)
- Affiliation/University (if mentioned in paper metadata or inferable from context)
- Research focus/area (infer from their work based on title and abstract)
- Seniority level: "junior" (PhD student/postdoc), "mid" (assistant professor/research scientist), or "senior" (associate/full professor, established researcher)

Return as JSON:
{{
  "researchers": [
    {{
      "name": "Full Name",
      "affiliation": "University/Institution",
      "research_focus": "Brief description of their research area",
      "seniority": "junior|mid|senior"
    }}
  ]
}}

Notes:
- If affiliation is not explicitly stated, use "Unknown" rather than guessing
- Research focus should be 2-3 sentences maximum
- Only include authors who appear to be active researchers (not just collaborators)
- Focus on first/last authors as they typically drive the research"""

    prompt = prompt_template.format(
        title=metadata.get('title', ''),
        authors=metadata.get('authors_raw', ''),
        abstract=metadata.get('summary', ''),
        arxiv_id=metadata.get('arxiv_id', ''),
        published_date=metadata.get('published_date', 'Unknown')
    )

    # Call LLM
    response = call_llm(
        client=client,
        prompt=prompt,
        model=config['llm']['model'],
        temperature=config['llm']['temperature'],
        max_tokens=config['llm']['max_tokens']
    )

    # Parse JSON response
    try:
        data = parse_json_response(response)
        researchers = data.get('researchers', [])

        # Add paper association to each researcher
        paper_id = metadata.get('arxiv_id', 'unknown')
        for researcher in researchers:
            researcher['papers'] = paper_id

        return researchers

    except Exception as e:
        print(f"Error parsing response for paper {metadata.get('arxiv_id', 'unknown')}: {e}")
        print(f"Raw response: {response[:500]}...")
        return []

def extract_researchers_from_citations(citations: List[Dict[str, Any]], client, config) -> List[Dict[str, Any]]:
    """Extract researchers from cited papers"""
    all_citation_researchers = []

    for citation in citations:
        if not citation.get('title') or not citation.get('authors'):
            continue

        # Create a simplified metadata dict for the citation
        citation_metadata = {
            'title': citation.get('title', ''),
            'authors_raw': citation.get('authors', ''),
            'summary': f"Cited paper: {citation.get('title', '')}",
            'arxiv_id': citation.get('arxiv_id', ''),
            'published_date': citation.get('year', 'Unknown')
        }

        # Extract researchers from this citation
        researchers = extract_researchers_from_paper_metadata(citation_metadata, client, config)

        # Mark these as from citations (could add a flag if needed)
        for researcher in researchers:
            researcher['papers'] = f"cited_in_{citation_metadata.get('arxiv_id', 'unknown')}"

        all_citation_researchers.extend(researchers)

        # Small delay to be respectful
        time.sleep(0.2)

    return all_citation_researchers

def aggregate_researchers(researchers_df):
    """Aggregate researchers by name, combining papers and keeping best info"""
    if researchers_df.empty:
        return pd.DataFrame(columns=['name', 'affiliation', 'research_focus', 'seniority', 'papers'])

    # Group by name (case-insensitive)
    aggregated = defaultdict(lambda: {
        'name': '',
        'affiliation': 'Unknown',
        'research_focus': '',
        'seniority': 'mid',  # default
        'papers': []
    })

    for _, researcher in researchers_df.iterrows():
        name_key = researcher['name'].strip().lower()

        # Update name (keep original casing)
        if not aggregated[name_key]['name']:
            aggregated[name_key]['name'] = researcher['name'].strip()

        # Update affiliation if we have one (prefer non-Unknown)
        if researcher.get('affiliation', 'Unknown') != 'Unknown' and aggregated[name_key]['affiliation'] == 'Unknown':
            aggregated[name_key]['affiliation'] = researcher['affiliation']

        # Update research focus if we have one
        if researcher.get('research_focus', '') and not aggregated[name_key]['research_focus']:
            aggregated[name_key]['research_focus'] = researcher['research_focus']

        # Update seniority
        if researcher.get('seniority'):
            aggregated[name_key]['seniority'] = researcher['seniority']

        # Add paper to list
        if researcher.get('papers'):
            aggregated[name_key]['papers'].append(researcher['papers'])

    # Convert back to DataFrame
    result_data = []
    for data in aggregated.values():
        # Remove duplicates from papers list and join with semicolons
        unique_papers = list(set(data['papers']))
        data['papers'] = ';'.join(sorted(unique_papers))
        result_data.append(data)

    return pd.DataFrame(result_data)

def process_pdf_file(pdf_path: Path, client, config) -> Tuple[Dict[str, Any], List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Process a single PDF file and extract metadata, researchers, and citation researchers"""
    print(f"Processing: {pdf_path.name}")

    # Extract text from PDF
    text = extract_text_from_pdf(str(pdf_path))
    if not text:
        print(f"Failed to extract text from {pdf_path}")
        return {}, [], []

    # Try to get arXiv ID from filename or text
    arxiv_id = extract_arxiv_id_from_filename(pdf_path.name) or extract_arxiv_id_from_text(text)

    # Parse paper metadata
    metadata = parse_paper_metadata(text, client, config)
    if arxiv_id and not metadata.get('arxiv_id'):
        metadata['arxiv_id'] = arxiv_id

    # Extract researchers from main paper
    main_researchers = extract_researchers_from_paper_metadata(metadata, client, config)

    # Extract citations and their researchers
    citations = extract_citations_from_text(text, client, config)
    citation_researchers = extract_researchers_from_citations(citations, client, config)

    return metadata, main_researchers, citation_researchers

def main():
    parser = argparse.ArgumentParser(description='Extract researchers from PDF directory')
    parser.add_argument('pdf_directory', help='Path to directory containing PDF files')
    parser.add_argument('--output', '-o', default='data/researchers.csv',
                       help='Output CSV file path (default: data/researchers.csv)')
    parser.add_argument('--config', '-c', help='Config file path (default: auto-detect)')
    parser.add_argument('--max-papers', '-m', type=int, help='Maximum number of PDFs to process')

    args = parser.parse_args()

    # Validate PDF directory
    pdf_dir = Path(args.pdf_directory)
    if not pdf_dir.exists() or not pdf_dir.is_dir():
        print(f"Error: {args.pdf_directory} is not a valid directory")
        return 1

    # Find all PDF files
    pdf_files = list(pdf_dir.glob('**/*.pdf'))
    if not pdf_files:
        print(f"No PDF files found in {args.pdf_directory}")
        return 1

    if args.max_papers:
        pdf_files = pdf_files[:args.max_papers]

    print(f"Found {len(pdf_files)} PDF files to process")

    # Load configuration
    try:
        config = load_config(args.config)
        print(f"Loaded config for domain: {config['domain']['name']}")
    except Exception as e:
        print(f"Error loading config: {e}")
        return 1

    # Initialize LLM client
    try:
        client = get_openai_client(config)
        print("LLM client initialized successfully")
    except Exception as e:
        print(f"Error initializing LLM client: {e}")
        return 1

    # Process PDFs
    all_researchers = []
    processed_count = 0

    for pdf_file in tqdm(pdf_files, desc="Processing PDFs"):
        try:
            metadata, main_researchers, citation_researchers = process_pdf_file(pdf_file, client, config)

            all_researchers.extend(main_researchers)
            all_researchers.extend(citation_researchers)

            processed_count += 1

            # Progress update
            total_researchers = len(all_researchers)
            print(f"Processed {processed_count} PDFs, extracted {total_researchers} researchers so far")

        except Exception as e:
            print(f"Error processing {pdf_file}: {e}")
            continue

    # Convert to DataFrame and aggregate
    if all_researchers:
        researchers_df = pd.DataFrame(all_researchers)
        final_researchers_df = aggregate_researchers(researchers_df)

        print(f"\nAfter aggregation: {len(final_researchers_df)} unique researchers")

        # Save results
        output_path = args.output
        save_csv_checkpoint(final_researchers_df, os.path.basename(output_path),
                           os.path.dirname(output_path) or 'data')
        print(f"✅ Successfully saved researchers to {output_path}")

        # Summary
        print("\n📊 Summary:")
        print(f"- PDFs processed: {processed_count}")
        print(f"- Main paper researchers: {len([r for r in all_researchers if not r['papers'].startswith('cited_in_')])}")
        print(f"- Citation researchers: {len([r for r in all_researchers if r['papers'].startswith('cited_in_')])}")
        print(f"- Unique researchers: {len(final_researchers_df)}")

    else:
        print("No researchers extracted from any PDFs")
        return 1

    return 0

if __name__ == '__main__':
    sys.exit(main())